#!/bin/bash

config=.config
command="$1"

while getopts ":c:" opt; do
  case $opt in
    c)
		config="$OPTARG"
    ;;
	s)
		command="-s"
	;;
	h)
		echo ""
		echo "options:"
		echo ""
		echo "   -c /path/to/config/file"
		echo "      if that parameter is missing it would look for .config file in the directory"
		echo "      the config file should contain the following settings:"
		echo ""
		echo "         host - remote host. example user@server.com"
		echo ""
		echo "         local_path - path where the local files would be synced"
		echo ""
		echo "         remote_path - path where the remote files are"
		echo ""
		echo "   -s - initial sync from local location to remote destination"
		echo "        note that on start it would sync back from the server first"
		echo ""
		echo ""
		echo ""
	;;
  esac
done

#load config
. $config

case $command in
	-s|--sync|sync)
		echo "Syncing start..."
		#initial sync from remote location to local
		rsync -zarh --delete $host:$remote_path $local_path
		if [[ $local_path_check ]]; then
			rsync -zarh --delete $local_path $local_path_check
		fi
		#sync files from local to remote location
		while true
		do
			if [[ $local_path_check ]]; then
				if ! diff -q $local_path $local_path_check &>/dev/null; then
			  		>&2
			  		rsync -zarh --delete $local_path $local_path_check
			  		rsync -zarh --delete $local_path $host:$remote_path
			  		date +"Change @ %c"
				fi
			else
				rsync -zarh --delete $local_path $host:$remote_path
				echo "Continuous syncing"
			fi 
			sleep 1
		done
	;;
esac
